spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/beyancodb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: false

server:
  port: 8080

beyanco:
  app:
    jwtSecret: beyAncoSecretKey2025ForJWTTokenGenerationAndVerification
    jwtExpirationMs: 86400000

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      beyanco: DEBUG
